name: CI

on: push

jobs:
  ruby-spec:
    name: Unit Specs
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby: [ruby-2.5, ruby-2.6, ruby-2.7]
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec spec/unit
  ruby-mutant:
    name: Mutation coverage
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        ruby: [ruby-2.5, ruby-2.6, ruby-2.7]
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec mutant run -- 'MPrelude*'
